#' text_list_translator
#'
#' @description This function compiles all the long text present in the app
#' It create a table with a language per column
#' To add message, you write text into a character vector for each language
#' and then you assemble the vectors into a table
#'
#' @return The return value is a table that you can export in a repertory
#' and charge top choose the message you want to display
#'
#' @export

text_list_translator <- function(){

  fr <- c(
    "En faisant le choix de travailler à partir des données mises à disposition avec l’outil, vous acceptez de faire l’analyse sur une concession fictive qui serait située dans le Golfe de Gascogne. Pour ce jeu de données fictif, on considère une concession en exploitation de 2000 à 2030, pour laquelle un suivi du compartiment halieutique a été mis en place tous les 5 ans. Le plan d’échantillonnage fictif prévoit l’échantillonnage de 10 stations dans la concession et 10 stations hors de la concession. Ce choix ne correspond pas à un plan d’échantillonnage qui aurait été élaboré en connaissance des conditions environnementales du site (i.e. faciès sédimentaires, habitats benthiques) et ne correspond donc pas aux recommandations du protocole halieutique de référence. Pour éviter toute confusion, les espèces présentes dans ce jeu de données sont fictives également. Ce jeu de données a une vocation pédagogique, il ne correspond à aucun cas réel et ne peut donc apparaître dans des documents à valeur administrative (i.e. rapports de suivi, état initial de l’environnement, état de référence avant travaux…).",
    "Ce tableau affiche les valeurs moyennes d’abondance, de biomasse, de richesse spécifique, des indicateurs de Shannon et de Simpson à l’intérieur de la concession, à l’extérieur de la concession, et au global pour chaque campagne (paragraphe 8.4.1 Protocole halieutique). Elles sont calculées à partir des valeurs obtenues en chaque station échantillonnée.",
    "Les graphiques proposés en dessous représentent les valeurs moyennes (point) et les percentiles 5 et 95 (barres hautes et basses) obtenus pour les mêmes indicateurs que ceux du tableau en fonction de la campagne sélectionnée (Protocole halieutique 8.4.1). L’intérêt de ces graphiques est  de pouvoir visualiser rapidement les différences entre la zone de concession et la zone de référence pour chaque indicateur.",
    "Ce tableau représente le pourcentage de chaque espèce présente pour chaque campagne d'échantillonnage (Protocole halieutique 8.4.1). Le tableau permet de suivre l'évolution des populations d'espèces au fil du temps et offre une perspective sur les tendances de population. En observant les variations des pourcentages d'espèces d'une année à  l'autre il est possible de détecter des changements écologiques  significatifs, tels que des fluctuations dans la biodiversité, des modifications des habitats ou des pressions environnementales. Il permet aussi  d’identifier les espèces qui dominent dans un écosystème donné ainsi que celles qui sont en déclin. Enfin, il permet d'évaluer l'impact de la gestion mise en place sur la communauté de poissons.",
    "La première figure représente l'abondance de chaque espèce participant au moins à 1% de l'abondance totale pour une campagne dans un histogramme ordonné par ordre d’abondance décroissante. Cela permet d'identifier les espèces dominantes, de visualiser les tendances temporelles, de détecter les variations saisonnières et annuelles, de comparer les données entre différentes campagnes et de communiquer les résultats de manière claire et concise.",
    "La deuxième figure est une courbe d'abondance cumulée en fonction du nombre d'espèces par ordre d'abondance décroissante.  L'abondance cumulée se réfère à la somme cumulative des abondances des  espèces dans un ensemble de données, en commençant par l'espèce la plus  abondante et en ajoutant successivement les abondances des espèces  suivantes dans l'ordre décroissant. La courbe d'abondance cumulée permet d'évaluer la diversité et la  répartition des espèces dans un écosystème ou dans un échantillon  biologique. Plus la courbe est plate, plus la communauté est  diversifiée alors qu’une courbe qui  monte rapidement puis s'aplatit indique une communauté où quelques espèces sont très abondantes tandis que la plupart des espèces sont  rares.",
    "La troisième figure est une courbe d'accumulation d'espèces (SAC). Ces courbes sont utilisées pour comparer les propriétés de diversité des ensembles de données sur les communautés en utilisant différentes fonctions d'accumulation. La méthode utilisée ici est la méthode aléatoire, qui permet de trouver la SAC moyenne et son écart-type à partir de permutations aléatoires des données, ou de sous-échantillonnage sans remplacement (Gotelli & Colwell 2001).",
    "Cette partie fournie un résumé statistique de la variable étudiée. Dans un premier temps le tableau renseigne sur le nombre de zéro présent, la longueur totale de la série de valeurs et un la fraction du nombre de zéros et valeurs manquantes sur le nombre de valeurs totales. Ensuite, il fournit également la moyenne, les extrêmes, l’écart-type et les quartiles de la série.",
    "La boite à moustache ou boxplot offre une autre représentation pour interpréter le lien entre la variable expliquée et les variables explicatives comme l'impact, l'année, l'enquête, la station et la saison. Dans les représentations graphiques de données statistiques, le boxplot est un moyen rapide de figurer le profil essentiel d'une série statistique quantitative. Le boxplot résume quelques indicateurs de position du caractère étudié (médiane, quartiles, minimum, maximum ou déciles). Il est souvent utilisé pour comparer rapidement deux séries. Dans GranulatShiny, la série de la variable expliquée dans la zone avec impact est comparé avec celle de  la zone sans impact.",
    "Cette partie est consacrée à la création d'un modèle pour l'analyse inférentielle. La variable analysée est rappelée en haut à gauche de l'onglet et peut être modifiée dans l'onglet représentation des données. Dans l'application il est possible de réaliser 3 types de tests inférentiels : GLMM, GLM, Permanova. La méthode GLMM est à prioriser (paragraphe 8.4.2 Protocole halieutique).",
    "Ces deux diagrammes analysent les résidus du modèle a posteriori. Plusieurs indicateurs de vérification sont associés à ces diagrammes et apparaissent en rouge si la modélisation ne s'est pas déroulée correctement",
    "La boite à moustache ou boxplot offre une autre représentation pour interpréter le lien entre la variable expliquée et les variables explicatives comme l'impact, la saison ou l'intéraction des deux. Si la Permanova a détecté un effet alors la p-value s'affiche en rouge en haut à gauche du graphique.",
    "L'outil antérieur construit par Mathis Cambreling fonctionne seulement pour le jeu de données ayant servi de base à ses calculs. L'outil n'étant pas généralisable, celui-ci a été retiré pour assurer la stabilité actuelle de l'application. Un autre outil est en cours de développement."
  )

  en <- c(
    "By agreeing to use the data provided by the tool, you are consenting to analyse a fictional concession in the Bay of Biscay. The dataset represents a concession that operates from 2000 to 2030, with monitoring conducted every 5 years. The sampling plan for this fictitious dataset involves selecting 10 stations within the concession and 10 stations outside of it. It is important to note that this sampling plan was not developed based on knowledge of the environmental conditions at the site, such as sedimentary facies and benthic habitats, and it does not align with the recommendations of the reference fisheries protocol. The species included in this dataset are also fictional. Therefore, this dataset is strictly for educational purposes and should not be used in any official documents such as monitoring reports or environmental assessments.",
    "This table shows the average values for abundance, biomass, species richness, Shannon and Simpson indicators inside the concession, outside the concession, and overall for each campaign (paragraph 8.4.1 Protocle Halieutique). They are calculated from the values obtained at each sampling station.",
    "The graphs below show the mean values (dots) and the 5 and 95 percentiles (high and low bars) obtained for the same indicators as those in the table according to the campaign selected (Protocle Halieutique 8.4.1). The purpose of these graphs is to quickly visualise the differences between the concession area and the reference area for each indicator.",
    "This table represents the percentage of each species present for each sampling campaign (Protocole Halieutique 8.4.1). The table makes it possible to monitor changes in species populations over time and provides a valuable perspective on population trends. By observing variations in species percentages from one year to the next, it is possible to detect significant ecological changes, such as fluctuations in biodiversity, changes in habitats or environmental pressures. It can also be used to identify which species are dominant in a given ecosystem and which are in decline. Finally, it can be used to assess the impact of the management measures put in place on the fish community.",
    "The first figure represents the abundance of each species accounting for at least 1% of the total abundance for a campaign in a histogram ordered by decreasing abundance. This makes it possible to identify the dominant species, visualise temporal trends, detect seasonal and annual variations, compare the data between different campaigns and communicate the results clearly and concisely.",
    "The second figure is a cumulative abundance curve as a function of the number of species in descending order of abundance. Cumulative abundance refers to the cumulative sum of species abundances in a data set, starting with the most abundant species and successively adding the abundances of the following species in descending order. The cumulative abundance curve is used to assess the diversity and distribution of species in an ecosystem or biological sample. The flatter the curve, the more diverse the community, whereas a curve that rises rapidly and then flattens out indicates a community where a few species are very abundant while most species are rare.",
    "The third figure is a species accumulation curve (SAC). This curves are used to compare diversity properties of community data sets using different accumulator functions. The method used here is random which finds the mean SAC and its standard deviation from random permutations of the data, or subsampling without replacement (Gotelli & Colwell 2001).",
    "This section provides a statistical summary of the variable studied. Firstly, the table provides information on the number of zeros present, the total length of the series of values and the fraction of the number of zeros and missing values in the total number of values. It then provides the mean, extremes, standard deviation and quartiles of the series.",
    "The boxplot offers another way of interpreting the relationship between the explained variable and explanatory variables such as impact, year, survey, station and season. In graphical representations of statistical data, the boxplot is a quick way of showing the essential profile of a quantitative statistical series. The boxplot summarises a few indicators of the position of the characteristic under study (median, quartiles, minimum, maximum or deciles). It is often used to quickly compare two series. In GranulatShiny, the series of the variable explained in the zone with impact is compared with that of the zone without impact.",
    "This section is devoted to creating a model for inferential analysis. The variable being analysed is shown at the top left of the tab and can be modified in the data representation tab. The application allows you to perform 3 types of inferential tests: GLMM, GLM and Permanova. The GLMM method should be given priority (paragraph 8.4.2 Protocole halieutique).",
    "These two diagrams analyse the model residuals a posteriori. Several verification indicators are associated with these diagrams and appear in red if the modelling was not carried out correctly",
    "The boxplot offers another way of interpreting the link between the variable being explained and the explanatory variables such as impact, season or the interaction of the two. If Permanova has detected an effect, the p-value is displayed in red at the top left of the graph.",
    "The previous tool built by Mathis Cambreling only works for the dataset used as the basis for his calculations. As the tool cannot be generalised, it has been withdrawn to ensure the current stability of the application. Another tool is currently under development."
    )

  list_translate <- data.frame(fr,en)

  saveRDS(list_translate, "data/list_translate.rds")

  return(list_translate)
}
